### ISSUE TITLE
As a user I want to requery previous datasets

### ISSUE THREAD

**Issue by jlfoster2** [ozone-development/meridian#583]
Approach will be to add ability in datahistory to do this

**Comment by tdressel** [comment]
Steps used to test:
Go to Data History icon on Menu Bar
Choose Requery button for previous queries and also previous uploaded data files.
RESULTS - The query tool should pop up on map with coordinates populated. Previous uploaded data files does not populate coordinates.
EXPECTED RESULTS -The query tool should pop up on map with coordinates populated. Previously uploaded data that displays in Data History should display the Requery button as grayed out since there is no bounding box associated.

**Comment by tdressel** [comment]
Passed on local branch.

**Comment by jrdrgz** [comment]
Added re-run button to the detailed view and added dataSource as a param to dynamically change the dataSource when the query tool opens. Thought about adding tooltips to the all the buttons but we can discuss later and create another ticket if agreed. Everything else looks good to me.
