### ISSUE TITLE
Bookmark - Add capability to save as bookmark  on a  new query inside the query tool

### ISSUE THREAD

**Issue by synAe** [ozone-development/meridian#596]
Add new:  the capability to save as bookmark on a new query

**Comment by synAe** [comment]
![uploads/95014351-b50c-46eb-ab72-109f65d7d324/#569_demo.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F95014351-b50c-46eb-ab72-109f65d7d324%2F%23569_demo.png)

**Comment by synAe** [comment]
Update from John:  for the time being, work on this enhancement is going to be put on hold, there are other code changes that may have a significant impact on this feature

**Comment by synAe** [comment]
Should now create a bookmark when checkbox is selected inside the query tool dialog.

**Comment by cwilmsen** [comment]
I do not see a pull request for this?

**Comment by cwilmsen** [comment]
Bookmarks should not be created on 'data.finish'. This means that 1. The bookmark is only created IF the query finishes 2. Even if the query will finished, the user has to wait for the query to finish to use it 3. (the big issue) Try this:
-Run a big query where you try to save the bookmark in the query tool
-Before it finishes, open the query tool and make sure that the 'Save as Bookmark' checkbox is off (defaulted that way)
-Wait for the original query to finish
Result: The original query is not saved because the checkbox is now not checked

The bookmark should be save as soon as the query is run, in the $submitButton.click() block. You will have all of the info you need there, and is the fastest and safest way to do it.

**Comment by jlfoster2** [comment]
closing this issue
